# Generated by Django 3.2.7 on 2021-10-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id_trip', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='idTrip')),
                ('t_from', models.CharField(max_length=30, verbose_name='From')),
                ('t_to', models.CharField(max_length=30, verbose_name='To')),
                ('date', models.CharField(max_length=18, verbose_name='Date')),
                ('duration', models.CharField(default='00:00', max_length=6, verbose_name='Duration')),
                ('service', models.CharField(choices=[('Basic', 'Basic'), ('Premium', 'Premium'), ('Elite', 'Elite')], default='Basic', max_length=8, verbose_name='Service')),
                ('rate', models.IntegerField(verbose_name='Rate')),
                ('id_vehicle', models.CharField(max_length=10, null=True, verbose_name='idCar')),
                ('company', models.CharField(max_length=40, verbose_name='Company')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False, verbose_name='idTicket')),
                ('get_ticket', models.BooleanField(default=False, verbose_name='Get')),
                ('dni_User', models.CharField(max_length=30, verbose_name='User')),
                ('id_trip', models.IntegerField(verbose_name='Route')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('dniUser', models.BigAutoField(primary_key=True, serialize=False, verbose_name='dniUser')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('last_name', models.CharField(default=' ', max_length=40, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.BigIntegerField(blank=True, verbose_name='Phone')),
                ('role', models.CharField(default='Usuario', max_length=8, verbose_name='Role')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
