# Generated by Django 3.2.7 on 2021-10-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dniUser',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='dniUser'),
        ),
    ]
