# Generated by Django 3.2.7 on 2021-10-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_alter_ticket_dni_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id_trip',
            field=models.CharField(max_length=20, verbose_name='idTrip'),
        ),
    ]
